version: '2'

services:
  security-example:
    image: 'andreformento/security'
    ports:
      - '8081:8081'
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
  mongodb:
    image: mongo:3
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
